


 

/**
 * 
 * https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/latest
 * 
 */
const as3latest = {
    "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/34202653",
    "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/34202653/assets",
    "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/34202653/assets{?name,label}",
    "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.5.0",
    "id": 34202653,
    "author": {
        "login": "F5Debbie",
        "id": 62711904,
        "node_id": "MDQ6VXNlcjYyNzExOTA0",
        "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/F5Debbie",
        "html_url": "https://github.com/F5Debbie",
        "followers_url": "https://api.github.com/users/F5Debbie/followers",
        "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
        "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
        "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
        "repos_url": "https://api.github.com/users/F5Debbie/repos",
        "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
        "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
        "type": "User",
        "site_admin": false
    },
    "node_id": "MDc6UmVsZWFzZTM0MjAyNjUz",
    "tag_name": "v1.5.0",
    "target_commitish": "master",
    "name": "",
    "draft": false,
    "prerelease": false,
    "created_at": "2020-11-19T22:05:58Z",
    "published_at": "2020-11-19T23:39:32Z",
    "assets": [
        {
            "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/28530842",
            "id": 28530842,
            "node_id": "MDEyOlJlbGVhc2VBc3NldDI4NTMwODQy",
            "name": "f5-appsvcs-templates-1.5.0-1.noarch.rpm",
            "label": null,
            "uploader": {
                "login": "F5Debbie",
                "id": 62711904,
                "node_id": "MDQ6VXNlcjYyNzExOTA0",
                "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/F5Debbie",
                "html_url": "https://github.com/F5Debbie",
                "followers_url": "https://api.github.com/users/F5Debbie/followers",
                "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                "repos_url": "https://api.github.com/users/F5Debbie/repos",
                "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                "type": "User",
                "site_admin": false
            },
            "content_type": "application/octet-stream",
            "state": "uploaded",
            "size": 5312073,
            "download_count": 143,
            "created_at": "2020-11-19T23:38:26Z",
            "updated_at": "2020-11-19T23:38:45Z",
            "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.5.0/f5-appsvcs-templates-1.5.0-1.noarch.rpm"
        },
        {
            "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/28530850",
            "id": 28530850,
            "node_id": "MDEyOlJlbGVhc2VBc3NldDI4NTMwODUw",
            "name": "f5-appsvcs-templates-1.5.0-1.noarch.rpm.sha256",
            "label": null,
            "uploader": {
                "login": "F5Debbie",
                "id": 62711904,
                "node_id": "MDQ6VXNlcjYyNzExOTA0",
                "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/F5Debbie",
                "html_url": "https://github.com/F5Debbie",
                "followers_url": "https://api.github.com/users/F5Debbie/followers",
                "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                "repos_url": "https://api.github.com/users/F5Debbie/repos",
                "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                "type": "User",
                "site_admin": false
            },
            "content_type": "application/octet-stream",
            "state": "uploaded",
            "size": 106,
            "download_count": 31,
            "created_at": "2020-11-19T23:38:45Z",
            "updated_at": "2020-11-19T23:38:46Z",
            "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.5.0/f5-appsvcs-templates-1.5.0-1.noarch.rpm.sha256"
        }
    ],
    "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.5.0",
    "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.5.0",
    "body": "Added\r\n\r\n* GUI: Support Markdown in schema descriptions\r\n* GUI: Clicking on an application name in the Application List tab now modifies the application\r\n* bigip-fast-templates: Add Microsoft Sharepoint template (experimental/beta)\r\n* bigip-fast-templates: Add Microsoft Exchange template (experimental/beta)\r\n* bigip-fast-templates: Add Microsoft ADFS template (experimental/beta)\r\n* bigip-fast-templates: Add Microsoft IIS template\r\n* bigip-fast-templates: Add SMTP template\r\n* bigip-fast-templates: Add LDAP template\r\n* bigip-fast-templates: Add firewall feature to DNS, TCP, and HTTP templates\r\n* bigip-fast-templates: Add configurable monitors to TCP and HTTP templates\r\n* bigip-fast-templates: Allow for more advanced pool member configuration in TCP and HTTP templates\r\n* Allow hiding templates from REST/GUI with bigipHideTemplate template property\r\n* Allow specifying a minimum AS3 version for a given template (bigipMinimumAS3 template property)\r\n\r\nFixed\r\n\r\n* GUI: Fix handling of undefined values in the base64 editor\r\n* worker: Fix hydrating enumFromBigip on multiple properties with \"items\" sub-properties\r\n\r\nChanged\r\n\r\n* Improve performance when working with many FAST applications\r\n* bigip-fast-templates: Improve prompts and descriptions of various parameters\r\n* GUI: Improve displaying errors when managing template sets\r\n* bigip-fast-templates: Update existing applications to use the new pool members definition\r\n* Update f5-fast-core from v0.8.0 to v0.9.0\r\n* driver: Add \"f5-appsvcs-templates\" userAgent string to AS3 declarations\r\n"
}



/**
 * 
 * https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases
 * 
 */
const fastReleases = [
    {
        "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/34202653",
        "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/34202653/assets",
        "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/34202653/assets{?name,label}",
        "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.5.0",
        "id": 34202653,
        "author": {
            "login": "F5Debbie",
            "id": 62711904,
            "node_id": "MDQ6VXNlcjYyNzExOTA0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/F5Debbie",
            "html_url": "https://github.com/F5Debbie",
            "followers_url": "https://api.github.com/users/F5Debbie/followers",
            "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
            "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
            "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
            "repos_url": "https://api.github.com/users/F5Debbie/repos",
            "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
            "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM0MjAyNjUz",
        "tag_name": "v1.5.0",
        "target_commitish": "master",
        "name": "",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-11-19T22:05:58Z",
        "published_at": "2020-11-19T23:39:32Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/28530842",
                "id": 28530842,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDI4NTMwODQy",
                "name": "f5-appsvcs-templates-1.5.0-1.noarch.rpm",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 5312073,
                "download_count": 144,
                "created_at": "2020-11-19T23:38:26Z",
                "updated_at": "2020-11-19T23:38:45Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.5.0/f5-appsvcs-templates-1.5.0-1.noarch.rpm"
            },
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/28530850",
                "id": 28530850,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDI4NTMwODUw",
                "name": "f5-appsvcs-templates-1.5.0-1.noarch.rpm.sha256",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 106,
                "download_count": 31,
                "created_at": "2020-11-19T23:38:45Z",
                "updated_at": "2020-11-19T23:38:46Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.5.0/f5-appsvcs-templates-1.5.0-1.noarch.rpm.sha256"
            }
        ],
        "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.5.0",
        "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.5.0",
        "body": "Added\r\n\r\n* GUI: Support Markdown in schema descriptions\r\n* GUI: Clicking on an application name in the Application List tab now modifies the application\r\n* bigip-fast-templates: Add Microsoft Sharepoint template (experimental/beta)\r\n* bigip-fast-templates: Add Microsoft Exchange template (experimental/beta)\r\n* bigip-fast-templates: Add Microsoft ADFS template (experimental/beta)\r\n* bigip-fast-templates: Add Microsoft IIS template\r\n* bigip-fast-templates: Add SMTP template\r\n* bigip-fast-templates: Add LDAP template\r\n* bigip-fast-templates: Add firewall feature to DNS, TCP, and HTTP templates\r\n* bigip-fast-templates: Add configurable monitors to TCP and HTTP templates\r\n* bigip-fast-templates: Allow for more advanced pool member configuration in TCP and HTTP templates\r\n* Allow hiding templates from REST/GUI with bigipHideTemplate template property\r\n* Allow specifying a minimum AS3 version for a given template (bigipMinimumAS3 template property)\r\n\r\nFixed\r\n\r\n* GUI: Fix handling of undefined values in the base64 editor\r\n* worker: Fix hydrating enumFromBigip on multiple properties with \"items\" sub-properties\r\n\r\nChanged\r\n\r\n* Improve performance when working with many FAST applications\r\n* bigip-fast-templates: Improve prompts and descriptions of various parameters\r\n* GUI: Improve displaying errors when managing template sets\r\n* bigip-fast-templates: Update existing applications to use the new pool members definition\r\n* Update f5-fast-core from v0.8.0 to v0.9.0\r\n* driver: Add \"f5-appsvcs-templates\" userAgent string to AS3 declarations\r\n"
    },
    {
        "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/32463603",
        "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/32463603/assets",
        "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/32463603/assets{?name,label}",
        "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.4.0",
        "id": 32463603,
        "author": {
            "login": "frslater",
            "id": 6587389,
            "node_id": "MDQ6VXNlcjY1ODczODk=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/6587389?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/frslater",
            "html_url": "https://github.com/frslater",
            "followers_url": "https://api.github.com/users/frslater/followers",
            "following_url": "https://api.github.com/users/frslater/following{/other_user}",
            "gists_url": "https://api.github.com/users/frslater/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/frslater/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/frslater/subscriptions",
            "organizations_url": "https://api.github.com/users/frslater/orgs",
            "repos_url": "https://api.github.com/users/frslater/repos",
            "events_url": "https://api.github.com/users/frslater/events{/privacy}",
            "received_events_url": "https://api.github.com/users/frslater/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTMyNDYzNjAz",
        "tag_name": "v1.4.0",
        "target_commitish": "master",
        "name": "v1.4.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-10-09T17:09:09Z",
        "published_at": "2020-10-12T17:02:21Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/26877926",
                "id": 26877926,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDI2ODc3OTI2",
                "name": "f5-appsvcs-templates-1.4.0-1.noarch.rpm",
                "label": null,
                "uploader": {
                    "login": "frslater",
                    "id": 6587389,
                    "node_id": "MDQ6VXNlcjY1ODczODk=",
                    "avatar_url": "https://avatars0.githubusercontent.com/u/6587389?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/frslater",
                    "html_url": "https://github.com/frslater",
                    "followers_url": "https://api.github.com/users/frslater/followers",
                    "following_url": "https://api.github.com/users/frslater/following{/other_user}",
                    "gists_url": "https://api.github.com/users/frslater/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/frslater/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/frslater/subscriptions",
                    "organizations_url": "https://api.github.com/users/frslater/orgs",
                    "repos_url": "https://api.github.com/users/frslater/repos",
                    "events_url": "https://api.github.com/users/frslater/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/frslater/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 5166545,
                "download_count": 376,
                "created_at": "2020-10-12T17:01:09Z",
                "updated_at": "2020-10-12T17:01:49Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.4.0/f5-appsvcs-templates-1.4.0-1.noarch.rpm"
            },
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/26878054",
                "id": 26878054,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDI2ODc4MDU0",
                "name": "f5-appsvcs-templates-1.4.0-1.noarch.rpm.sha256",
                "label": null,
                "uploader": {
                    "login": "frslater",
                    "id": 6587389,
                    "node_id": "MDQ6VXNlcjY1ODczODk=",
                    "avatar_url": "https://avatars0.githubusercontent.com/u/6587389?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/frslater",
                    "html_url": "https://github.com/frslater",
                    "followers_url": "https://api.github.com/users/frslater/followers",
                    "following_url": "https://api.github.com/users/frslater/following{/other_user}",
                    "gists_url": "https://api.github.com/users/frslater/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/frslater/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/frslater/subscriptions",
                    "organizations_url": "https://api.github.com/users/frslater/orgs",
                    "repos_url": "https://api.github.com/users/frslater/repos",
                    "events_url": "https://api.github.com/users/frslater/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/frslater/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 106,
                "download_count": 62,
                "created_at": "2020-10-12T17:05:33Z",
                "updated_at": "2020-10-12T17:05:34Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.4.0/f5-appsvcs-templates-1.4.0-1.noarch.rpm.sha256"
            }
        ],
        "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.4.0",
        "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.4.0",
        "body": "Added\r\n* Allow retrieving failed application submissions to be modified and resubmitted\r\n* Added a DNS template to bigipi-fast-templates\r\n* Add iRules to both TCP and HTTP templates\r\n \r\nFixed\r\n* Fixed REST worker error when loading a template with schema that has no properties defined\r\n* Cleanup task messages on BIG-IPs with multiple tenants\r\n* Fixed 404 error when attempting to load the GUI before restnoded is ready\r\n \r\nChanged\r\n* Use template merging to reduce duplication between TCP and HTTP templates\r\n* Update style to better match BIG-IP GUI\r\n* Make editor form titles more consistent in the Deploy tab"
    },
    {
        "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/30584338",
        "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/30584338/assets",
        "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/30584338/assets{?name,label}",
        "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.3.0",
        "id": 30584338,
        "author": {
            "login": "F5Debbie",
            "id": 62711904,
            "node_id": "MDQ6VXNlcjYyNzExOTA0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/F5Debbie",
            "html_url": "https://github.com/F5Debbie",
            "followers_url": "https://api.github.com/users/F5Debbie/followers",
            "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
            "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
            "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
            "repos_url": "https://api.github.com/users/F5Debbie/repos",
            "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
            "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTMwNTg0MzM4",
        "tag_name": "v1.3.0",
        "target_commitish": "master",
        "name": "v1.3.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-08-31T22:18:06Z",
        "published_at": "2020-09-02T13:15:01Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/24739561",
                "id": 24739561,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDI0NzM5NTYx",
                "name": "f5-appsvcs-templates-1.3.0-1.noarch.rpm",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 5024075,
                "download_count": 870,
                "created_at": "2020-09-02T13:14:30Z",
                "updated_at": "2020-09-02T13:14:48Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.3.0/f5-appsvcs-templates-1.3.0-1.noarch.rpm"
            },
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/25326095",
                "id": 25326095,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDI1MzI2MDk1",
                "name": "f5-appsvcs-templates-1.3.0-1.noarch.rpm.sha256",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 106,
                "download_count": 54,
                "created_at": "2020-09-10T15:25:50Z",
                "updated_at": "2020-09-10T15:25:51Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.3.0/f5-appsvcs-templates-1.3.0-1.noarch.rpm.sha256"
            }
        ],
        "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.3.0",
        "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.3.0",
        "body": "Added\r\n\r\n* Support enumFromBigip on array items\r\n* GUI: Add textboxes that can output base64 strings when a template is rendered\r\n* Templates: Add option to get variable values from HTTP requests\r\n* GUI: Use JSON Editor 'select' format for arrays of unique enum items\r\n* bigip-fast-templates: Support using the same TCP profile for both ingress and egress traffic\r\n\r\nFixed\r\n\r\n* bigip-fast-templates/tcp: Fix enumFromBigip for monitor_name\r\n* Fix 500 error when invalid template sets are used\r\n* GUI: Improve filtering extra properties when using template merging\r\n* GUI: Improve form render order when using allOf\r\n\r\nChanged\r\n\r\n* Use AS3's optimistic locking to detect synchronization issues between FAST and AS3\r\n* Templates: Return an empty array instead of undefined when transforming an undefined array\r\n"
    },
    {
        "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/28687407",
        "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/28687407/assets",
        "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/28687407/assets{?name,label}",
        "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.2.0",
        "id": 28687407,
        "author": {
            "login": "F5Debbie",
            "id": 62711904,
            "node_id": "MDQ6VXNlcjYyNzExOTA0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/F5Debbie",
            "html_url": "https://github.com/F5Debbie",
            "followers_url": "https://api.github.com/users/F5Debbie/followers",
            "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
            "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
            "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
            "repos_url": "https://api.github.com/users/F5Debbie/repos",
            "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
            "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTI4Njg3NDA3",
        "tag_name": "v1.2.0",
        "target_commitish": "master",
        "name": "v1.2.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-07-17T18:36:52Z",
        "published_at": "2020-07-17T18:56:09Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/22990252",
                "id": 22990252,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDIyOTkwMjUy",
                "name": "f5-appsvcs-templates-1.2.0-1.noarch.rpm",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 4422556,
                "download_count": 637,
                "created_at": "2020-07-17T18:54:58Z",
                "updated_at": "2020-07-17T18:55:14Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.2.0/f5-appsvcs-templates-1.2.0-1.noarch.rpm"
            },
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/22990268",
                "id": 22990268,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDIyOTkwMjY4",
                "name": "f5-appsvcs-templates-1.2.0-1.noarch.rpm.sha256",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 111,
                "download_count": 77,
                "created_at": "2020-07-17T18:55:14Z",
                "updated_at": "2020-07-17T18:55:14Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.2.0/f5-appsvcs-templates-1.2.0-1.noarch.rpm.sha256"
            }
        ],
        "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.2.0",
        "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.2.0",
        "body": "Added\r\n\r\n* Add confirmation dialogs to dangerous operations\r\n* Add spinner loader to indicate when page is loading\r\n* Improve error output when a template fails to render in the GUI\r\n* Improve error output for bad \"name\" property on POST to /applications\r\n* Improve error output for missing \"name\" or \"parameters\" property on POST to /applications\r\n* Add showDisabled query parameter to GET on /templatesets for showing disabled template sets\r\n* Support PATCH on /applications/{tenant}/{app} endpoint for partial modifications of existing applications\r\n* Add template set hash (setHash) to application data\r\n* Add accordion to the template sets on the deploy page\r\n* Add additional status reporting for tasks in the Deploy Log\r\n* Add filter to Templates Page\r\n* Add disabled templatesets to the Templates Page\r\n* Add install button to templatesets\r\n\r\nFixed\r\n\r\n* Stop printing empty strings to the console\r\n* Work-around iControl replacing error messages with \"HTML Tag-like Content in Request URL/Body\"\r\n* Fix broken alignment across all tables\r\n\r\nChanged\r\n\r\n* Reduce latency on the /templatesets endpoint\r\n* Restrict allowed characters for tenant and application names on bigip-fast-templates\r\n* Stop allowing the deletion of in-use template sets"
    },
    {
        "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/27113449",
        "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/27113449/assets",
        "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/27113449/assets{?name,label}",
        "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.1.0",
        "id": 27113449,
        "author": {
            "login": "F5Debbie",
            "id": 62711904,
            "node_id": "MDQ6VXNlcjYyNzExOTA0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/F5Debbie",
            "html_url": "https://github.com/F5Debbie",
            "followers_url": "https://api.github.com/users/F5Debbie/followers",
            "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
            "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
            "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
            "repos_url": "https://api.github.com/users/F5Debbie/repos",
            "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
            "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTI3MTEzNDQ5",
        "tag_name": "v1.1.0",
        "target_commitish": "master",
        "name": "v1.1.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-06-01T18:07:53Z",
        "published_at": "2020-06-01T21:55:55Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/21266454",
                "id": 21266454,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDIxMjY2NDU0",
                "name": "f5-appsvcs-templates-1.1.0-1.noarch.rpm",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 4954266,
                "download_count": 1443,
                "created_at": "2020-06-01T21:54:06Z",
                "updated_at": "2020-06-01T21:54:24Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.1.0/f5-appsvcs-templates-1.1.0-1.noarch.rpm"
            },
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/21266465",
                "id": 21266465,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDIxMjY2NDY1",
                "name": "f5-appsvcs-templates-1.1.0-1.noarch.rpm.sha256",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 106,
                "download_count": 113,
                "created_at": "2020-06-01T21:54:25Z",
                "updated_at": "2020-06-01T21:54:25Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.1.0/f5-appsvcs-templates-1.1.0-1.noarch.rpm.sha256"
            }
        ],
        "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.1.0",
        "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.1.0",
        "body": "Added\r\n\r\n * Support DELETE on /applications endpoint (deletes all applications managed by FAST)\r\n * Support DELETE on /templatesets endpoint (deletes all installed templates)\r\n * Support combining templates via oneOf/allOf/anyOf\r\n * Support $ref in template definitions (http $refs are not supported)\r\n\r\nFixed\r\n\r\n * Fix enumFromBigip error when endpoint does not contain \"items\"\r\n\r\nChanged\r\n\r\n * Request IDs in the REST worker log have been switch from uuid4 IDs to an incrementing counter\r\n * Deleting a base template set persists through a reboot\r\n * Improved error reporting when a template fails to load\r\n * GUI updated to better match the look and feel of the rest of the BIG-IP GUI\r\n * Empty template sets no longer pass validation\r\n * Under Templates, moved 'supported' away from middle column into a tooltipped f5 logo\r\n * Under Templates, more than two apps will now be expandableems”"
    },
    {
        "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/26027292",
        "assets_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/26027292/assets",
        "upload_url": "https://uploads.github.com/repos/F5Networks/f5-appsvcs-templates/releases/26027292/assets{?name,label}",
        "html_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.0.0",
        "id": 26027292,
        "author": {
            "login": "F5Debbie",
            "id": 62711904,
            "node_id": "MDQ6VXNlcjYyNzExOTA0",
            "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/F5Debbie",
            "html_url": "https://github.com/F5Debbie",
            "followers_url": "https://api.github.com/users/F5Debbie/followers",
            "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
            "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
            "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
            "repos_url": "https://api.github.com/users/F5Debbie/repos",
            "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
            "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTI2MDI3Mjky",
        "tag_name": "v1.0.0",
        "target_commitish": "master",
        "name": "v1.0.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-04-29T18:56:07Z",
        "published_at": "2020-04-29T23:49:16Z",
        "assets": [
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/20281476",
                "id": 20281476,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDIwMjgxNDc2",
                "name": "f5-appsvcs-templates-1.0.0-1.noarch.rpm",
                "label": null,
                "uploader": {
                    "login": "F5Debbie",
                    "id": 62711904,
                    "node_id": "MDQ6VXNlcjYyNzExOTA0",
                    "avatar_url": "https://avatars2.githubusercontent.com/u/62711904?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/F5Debbie",
                    "html_url": "https://github.com/F5Debbie",
                    "followers_url": "https://api.github.com/users/F5Debbie/followers",
                    "following_url": "https://api.github.com/users/F5Debbie/following{/other_user}",
                    "gists_url": "https://api.github.com/users/F5Debbie/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/F5Debbie/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/F5Debbie/subscriptions",
                    "organizations_url": "https://api.github.com/users/F5Debbie/orgs",
                    "repos_url": "https://api.github.com/users/F5Debbie/repos",
                    "events_url": "https://api.github.com/users/F5Debbie/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/F5Debbie/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 4858078,
                "download_count": 509,
                "created_at": "2020-04-29T23:54:41Z",
                "updated_at": "2020-04-29T23:54:58Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.0.0/f5-appsvcs-templates-1.0.0-1.noarch.rpm"
            },
            {
                "url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/releases/assets/20281519",
                "id": 20281519,
                "node_id": "MDEyOlJlbGVhc2VBc3NldDIwMjgxNTE5",
                "name": "f5-appsvcs-templates-1.0.0-1.noarch.rpm.sha256",
                "label": null,
                "uploader": {
                    "login": "JosephPJordan",
                    "id": 22331467,
                    "node_id": "MDQ6VXNlcjIyMzMxNDY3",
                    "avatar_url": "https://avatars0.githubusercontent.com/u/22331467?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/JosephPJordan",
                    "html_url": "https://github.com/JosephPJordan",
                    "followers_url": "https://api.github.com/users/JosephPJordan/followers",
                    "following_url": "https://api.github.com/users/JosephPJordan/following{/other_user}",
                    "gists_url": "https://api.github.com/users/JosephPJordan/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/JosephPJordan/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/JosephPJordan/subscriptions",
                    "organizations_url": "https://api.github.com/users/JosephPJordan/orgs",
                    "repos_url": "https://api.github.com/users/JosephPJordan/repos",
                    "events_url": "https://api.github.com/users/JosephPJordan/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/JosephPJordan/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "content_type": "application/octet-stream",
                "state": "uploaded",
                "size": 106,
                "download_count": 417,
                "created_at": "2020-04-29T23:58:02Z",
                "updated_at": "2020-04-29T23:58:02Z",
                "browser_download_url": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.0.0/f5-appsvcs-templates-1.0.0-1.noarch.rpm.sha256"
            }
        ],
        "tarball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/tarball/v1.0.0",
        "zipball_url": "https://api.github.com/repos/F5Networks/f5-appsvcs-templates/zipball/v1.0.0",
        "body": "Updated the documentation for FAST v1.0. This release contains the following changes:\r\n* Added improved support for external schema references when using the FAST CLI\r\n* Added packageTemplateSet commant to the FAST CLI\r\n* Added functionality for POST to/applications which can now take an array of applications\r\n* Added SNAT, Persistance and support for various profiles to the HTTP and TCP templates\r\n* Improved error reporting when schema validation fails using the FAST CLI\r\n* Improved titles and descriptions in the bigip-fast-templates\r\n* Template sections now default to arrays instead of booleans which can be overwritten by using a section variable type of “boolean”\r\n\r\nIssues Resolved:\r\n* GUI elements were not showing/hiding consistently\r\n* JSHINT errors were showing up in restnoded log when loading the REST worker\r\n* Aiv warnings when using text, hidden or password formats"
    }
]